[package]
name = "under-benchmark"
version = "0.1.0"
authors = ["Jeremy Rodi <me@retroc.at>"]
edition = "2018"

[dependencies]
under = { git = "https://github.com/medcat/under.git", branch = "main" }
tokio = { version = "1.12.0", features = ["full"] }
